### ISSUE TITLE
Составить сценарии тестирования для репозиториев

### ISSUE THREAD

**Issue by Mozzarella123** [Mozzarella123/calculator#171]
Написать сценарии тестирования для интерфейса репозитория.
```
public interface IRepository<T> : INotifyCollectionChanged
    {
        IEnumerable<T> Collection { get; }
        void Update(T obj);
        bool Remove(T obj);
        void Add(T obj);
        void Clear();
    }
```
**Как работает репозиторий**
Репозиторий - это хранилище данных. С помощью доступных методов у репозитория мы с этими данными работаем(добавляем, удаляем, редактируем).  
Также при каждого из методов срабатывает событие CollectionChanged, реализация интерфейса INotifyCollectionChanged. Смотри как работает ObservableCollecton
Пример реализации интерфейса: https://github.com/Mozzarella123/calculator/blob/Task%23179/BuildingCalculator/BuildingCalculator/Data/RepositoryBase.cs

**Пример:**
Метод Add.

Входные данные: объект типа T,null

Выходные данные: количество элементов в коллекции увеличилось на один или exception

_По поводу ожидаемого значения в исключительных ситуациях, оставлять пустую ячейку или спрашивать тимлида_

**Comment by Mozzarella123** [comment]
@CallmeMaybaha Добавил пример

**Comment by CallmeMaybaha** [comment]
https://docs.google.com/spreadsheets/d/13pMXXo0HOu_HSLTMyejk5VLa0y-248OVYfXAru1J1ig/edit#gid=0

**Comment by Mozzarella123** [comment]
@CallmeMaybaha добавить проверку параметров которые приходят в событии CollectionChanged, допустим в методе Update пришёл тот же элемент, который запрашивался на обновление

**Comment by CallmeMaybaha** [comment]
@Mozzarella123 Добавил
