### ISSUE TITLE
FormulaEditor не вносит введеную формулу в свойство FormulaBinding

### ISSUE THREAD

**Issue by ValyaBuldozer** [Mozzarella123/calculator#204]
Ветвь Task#201
При вводе любого выражения FormulaBinding остается null даже в самом юк. 
![image](https://user-images.githubusercontent.com/30180012/43632121-e593014c-970d-11e8-94d3-3a13e386e256.png)

![image](https://user-images.githubusercontent.com/30180012/43632186-0f069d5e-970e-11e8-8da1-606fc784bd76.png)

Файлы : EmpployeeTypeView.xaml , vm: EmployeeTypeViewModel

**Comment by Mozzarella123** [comment]
Когда создается новая ViewModel нужно инициализировать экземпляр формулы отличный от Null
